# Generated by Django 4.0.3 on 2022-03-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
