# Generated by Django 4.0.3 on 2022-04-02 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userprofile_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
