# Generated by Django 4.0.3 on 2022-04-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
